#默认配置环境 启动配置项
spring:
  profiles:
    active: devsingle

---
#开发环境(集群版)
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
server:
  port: 7001

eureka:
  instance:
    hostname: erueka7001.com           # eureka 服务端实例名称
  client:
    register-with-eureka: false   # false不向注册中心注册自己
    fetch-registry: false         # false表示自己就是注册中心，我的职责是维护服务实例，并不需要检索到eureka服务
    service-url:
      defaultZone: http://erueka7002.com:7002/eureka/,http://erueka7003.com:7003/eureka/ # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（集群）。


---
#开发环境(单机版)
spring:
  profiles: devsingle
  application:
    name: microservicecloud-config-eureka-client
server:
  port: 7001

eureka:
  instance:
    hostname: erueka7001.com           # eureka 服务端实例名称
  client:
    register-with-eureka: false   # false不向注册中心注册自己
    fetch-registry: false         # false表示自己就是注册中心，我的职责是维护服务实例，并不需要检索到eureka服务
    service-url:
      defaultZone: http://erueka7002.com:7002/eureka/ # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
