#默认配置环境 启动配置项
spring:
  profiles:
    active: devsingle

---
#开发环境（集群）
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clouddb01
    username: root
    password: root
    dbcp2:
      min-idle: 5         # 数据库连接池最小维持数
      initial-size: 5     # 初始化连接数
      max-total: 5        # 最大连接数
      max-wait-millis: 200 #等待链接获取的最大超时时间

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper文件所在目录
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.bigeyes.springcloud.entities    # 所有Entity别名类所在包

eureka:
  client:
    service-url:
      defaultZone: http://erueka7001.com:7001/eureka/,http://erueka7002.com:7002/eureka/,http://erueka7003.com:7003/eureka/
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept:8001                # 修改服务名称
    prefer-ip-address: true                                 # 显示IP地址

info:
  app.name: bigeyes-microservicecloud
  company.name: www.bigeyes.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
#开发环境（单机）
server:
  port: 8001

spring:
  profiles: devsingle
  application:
    name: microservicecloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clouddb01
    username: root
    password: root
    dbcp2:
      min-idle: 5         # 数据库连接池最小维持数
      initial-size: 5     # 初始化连接数
      max-total: 5        # 最大连接数
      max-wait-millis: 200 #等待链接获取的最大超时时间

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper文件所在目录
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.bigeyes.springcloud.entities    # 所有Entity别名类所在包

eureka:
  client:
    service-url:
      #defaultZone: http://erueka7001.com:7001/eureka/,http://erueka7002.com:7002/eureka/,http://erueka7003.com:7003/eureka/
      defaultZone: http://erueka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept:8001                # 修改服务名称
    prefer-ip-address: true                                 # 显示IP地址

info:
  app.name: bigeyes-microservicecloud
  company.name: www.bigeyes.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
